version: 2.1

workflows:
  node-build:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:14.15.1

    steps:
      - checkout
      - restore_cache:
          key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn --version)"
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Build
          command: yarn build
      - save_cache:
          key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/workspace/node_modules
            - ~/.cache/yarn/